apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: go-toy-shop
  namespace: toyshop

spec:
  rules:
  - http:
      paths:

      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-toy-shop
            port:
              number: 80
